version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: laravel_sqlserver
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: 62032597Hz
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1433:1433"
  laravel:
    build: .
    container_name: laravel
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - sqlserver

volumes:
  sqlserverdata: