-- Vista para Facturas Pendientes
-- Esta vista muestra las facturas pendientes de pago

IF EXISTS (SELECT * FROM sys.views WHERE name = 'vw_facturas_pendientes')
    DROP VIEW vw_facturas_pendientes
GO

CREATE VIEW vw_facturas_pendientes AS
SELECT TOP (100) PERCENT 
    dbo.MAEEDO.TIDO AS TIPO_DOCTO, 
    dbo.MAEEDO.NUDO AS NRO_DOCTO, 
    dbo.MAEEDO.ENDO AS CODIGO, 
    dbo.MAEEN.NOKOEN AS CLIENTE, 
    dbo.MAEEDO.SUDO AS SUC, 
    dbo.MAEEDO.FEEMDO AS EMISION, 
    dbo.MAEEDO.FE01VEDO AS P_VCMTO, 
    dbo.MAEEDO.FEULVEDO AS U_VCMTO, 
    CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) AS DIAS, 
    dbo.MAEEN.FOEN AS FONO, 
    dbo.MAEEN.DIEN AS DIRECCION, 
    dbo.TABCI.NOKOCI AS REGION, 
    dbo.TABCM.NOKOCM AS COMUNA, 
    ISNULL(dbo.TABFU.NOKOFU, 'SIN VENDEDOR ASIG.') AS VENDEDOR, 
    CASE WHEN dbo.MAEEDO.TIDO = 'NCV' THEN dbo.MAEEDO.VABRDO * - 1 ELSE dbo.MAEEDO.VABRDO END AS VALOR, 
    CASE WHEN dbo.MAEEDO.TIDO = 'NCV' THEN dbo.MAEEDO.VAABDO * - 1 ELSE dbo.MAEEDO.VAABDO END AS ABONOS, 
    CASE WHEN dbo.MAEEDO.TIDO = 'NCV' AND (dbo.MAEEDO.VABRDO <> dbo.MAEEDO.VAABDO) AND CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN - 7 AND - 1 THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * - 1 
         WHEN dbo.MAEEDO.TIDO <> 'NCV' AND (dbo.MAEEDO.VABRDO <> dbo.MAEEDO.VAABDO) AND CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) < - 7 THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * - 1 
         WHEN dbo.MAEEDO.TIDO <> 'NCV' AND (dbo.MAEEDO.VABRDO <> dbo.MAEEDO.VAABDO) AND CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) < - 7 THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * 1 
         ELSE 0 END AS POR_VENCER, 
    CASE WHEN dbo.MAEEDO.TIDO = 'NCV' AND (dbo.MAEEDO.VABRDO <> dbo.MAEEDO.VAABDO) AND CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) > - 1 THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * - 1 
         WHEN dbo.MAEEDO.TIDO <> 'NCV' AND (dbo.MAEEDO.VABRDO <> dbo.MAEEDO.VAABDO) AND CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) > - 1 THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * 1 
         ELSE 0 END AS VENCIDO, 
    CASE WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * - 1 ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) END AS SALDO, 
    CASE WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) < - 8 THEN 'VIGENTE' 
         WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN - 7 AND - 1 THEN 'POR VENCER' 
         WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN 0 AND 7 THEN 'VENCIDO' 
         WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN 8 AND 30 THEN 'MOROSO' 
         ELSE 'BLOQUEAR' END AS ESTADO, 
    dbo.TABFU.KOFU, 
    dbo.MAEEN.KOFUEN
FROM dbo.TABFU 
RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
LEFT OUTER JOIN dbo.TABCM ON dbo.MAEEN.CIEN = dbo.TABCM.KOCI AND dbo.MAEEN.CMEN = dbo.TABCM.KOCM 
RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
LEFT OUTER JOIN dbo.TABCI ON dbo.MAEEN.CIEN = dbo.TABCI.KOCI 
WHERE (dbo.MAEEDO.EMPRESA = '01') 
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV' OR dbo.MAEEDO.TIDO = 'NVV') 
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO) 
ORDER BY DIAS
GO

-- Verificar que la vista se creó correctamente
SELECT TOP 5 * FROM vw_facturas_pendientes WHERE KOFU = 'GOP'
GO
