-- =============================================
-- Query para identificar vendedor con más datos
-- GesPro Raviera - Sistema de Ventas
-- =============================================

-- Query 1: Vendedores con más NVV pendientes
SELECT 
    TABFU.KOFU AS CODIGO_VENDEDOR,
    TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    COUNT(*) AS TOTAL_NVV_PENDIENTES,
    SUM(MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1) AS UNIDADES_PENDIENTES,
    SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_PENDIENTE
FROM dbo.MAEDDO 
INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
WHERE (dbo.MAEDDO.TIDO = 'NVV') 
    AND (dbo.MAEDDO.LILG = 'SI') 
    AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
    AND (dbo.MAEDDO.KOPRCT <> 'D') 
    AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
GROUP BY TABFU.KOFU, TABFU.NOKOFU
ORDER BY TOTAL_NVV_PENDIENTES DESC, VALOR_PENDIENTE DESC;

-- Query 2: Vendedores con más facturas pendientes
SELECT 
    TABFU.KOFU AS CODIGO_VENDEDOR,
    TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    COUNT(*) AS TOTAL_FACTURAS_PENDIENTES,
    SUM(CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
        ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
    END) AS SALDO_TOTAL_PENDIENTE
FROM dbo.TABFU 
RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
WHERE (dbo.MAEEDO.EMPRESA = '01') 
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
    AND TABFU.KOFU IS NOT NULL
GROUP BY TABFU.KOFU, TABFU.NOKOFU
ORDER BY TOTAL_FACTURAS_PENDIENTES DESC, SALDO_TOTAL_PENDIENTE DESC;

-- Query 3: Resumen combinado de vendedores (TOP 10)
WITH NVV_Stats AS (
    SELECT 
        TABFU.KOFU AS CODIGO_VENDEDOR,
        TABFU.NOKOFU AS NOMBRE_VENDEDOR,
        COUNT(*) AS TOTAL_NVV_PENDIENTES,
        SUM(MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1) AS UNIDADES_PENDIENTES,
        SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_NVV_PENDIENTE
    FROM dbo.MAEDDO 
    INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
    INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
    WHERE (dbo.MAEDDO.TIDO = 'NVV') 
        AND (dbo.MAEDDO.LILG = 'SI') 
        AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
        AND (dbo.MAEDDO.KOPRCT <> 'D') 
        AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
    GROUP BY TABFU.KOFU, TABFU.NOKOFU
),
Facturas_Stats AS (
    SELECT 
        TABFU.KOFU AS CODIGO_VENDEDOR,
        TABFU.NOKOFU AS NOMBRE_VENDEDOR,
        COUNT(*) AS TOTAL_FACTURAS_PENDIENTES,
        SUM(CASE 
            WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
            ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
        END) AS SALDO_FACTURAS_PENDIENTE
    FROM dbo.TABFU 
    RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
    RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
    WHERE (dbo.MAEEDO.EMPRESA = '01') 
        AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
        AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
        AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
        AND TABFU.KOFU IS NOT NULL
    GROUP BY TABFU.KOFU, TABFU.NOKOFU
)
SELECT TOP 10
    COALESCE(n.CODIGO_VENDEDOR, f.CODIGO_VENDEDOR) AS CODIGO_VENDEDOR,
    COALESCE(n.NOMBRE_VENDEDOR, f.NOMBRE_VENDEDOR) AS NOMBRE_VENDEDOR,
    ISNULL(n.TOTAL_NVV_PENDIENTES, 0) AS TOTAL_NVV_PENDIENTES,
    ISNULL(n.UNIDADES_PENDIENTES, 0) AS UNIDADES_PENDIENTES,
    ISNULL(n.VALOR_NVV_PENDIENTE, 0) AS VALOR_NVV_PENDIENTE,
    ISNULL(f.TOTAL_FACTURAS_PENDIENTES, 0) AS TOTAL_FACTURAS_PENDIENTES,
    ISNULL(f.SALDO_FACTURAS_PENDIENTE, 0) AS SALDO_FACTURAS_PENDIENTE,
    (ISNULL(n.TOTAL_NVV_PENDIENTES, 0) + ISNULL(f.TOTAL_FACTURAS_PENDIENTES, 0)) AS TOTAL_DOCUMENTOS,
    (ISNULL(n.VALOR_NVV_PENDIENTE, 0) + ISNULL(f.SALDO_FACTURAS_PENDIENTE, 0)) AS VALOR_TOTAL_PENDIENTE
FROM NVV_Stats n
FULL OUTER JOIN Facturas_Stats f ON n.CODIGO_VENDEDOR = f.CODIGO_VENDEDOR
ORDER BY TOTAL_DOCUMENTOS DESC, VALOR_TOTAL_PENDIENTE DESC;

-- Query 4: Vendedor con más datos (RECOMENDADO PARA PRUEBAS)
SELECT TOP 1
    COALESCE(n.CODIGO_VENDEDOR, f.CODIGO_VENDEDOR) AS CODIGO_VENDEDOR_RECOMENDADO,
    COALESCE(n.NOMBRE_VENDEDOR, f.NOMBRE_VENDEDOR) AS NOMBRE_VENDEDOR_RECOMENDADO,
    ISNULL(n.TOTAL_NVV_PENDIENTES, 0) AS TOTAL_NVV_PENDIENTES,
    ISNULL(f.TOTAL_FACTURAS_PENDIENTES, 0) AS TOTAL_FACTURAS_PENDIENTES,
    (ISNULL(n.TOTAL_NVV_PENDIENTES, 0) + ISNULL(f.TOTAL_FACTURAS_PENDIENTES, 0)) AS TOTAL_DOCUMENTOS,
    (ISNULL(n.VALOR_NVV_PENDIENTE, 0) + ISNULL(f.SALDO_FACTURAS_PENDIENTE, 0)) AS VALOR_TOTAL_PENDIENTE
FROM (
    SELECT 
        TABFU.KOFU AS CODIGO_VENDEDOR,
        TABFU.NOKOFU AS NOMBRE_VENDEDOR,
        COUNT(*) AS TOTAL_NVV_PENDIENTES,
        SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_NVV_PENDIENTE
    FROM dbo.MAEDDO 
    INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
    INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
    WHERE (dbo.MAEDDO.TIDO = 'NVV') 
        AND (dbo.MAEDDO.LILG = 'SI') 
        AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
        AND (dbo.MAEDDO.KOPRCT <> 'D') 
        AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
    GROUP BY TABFU.KOFU, TABFU.NOKOFU
) n
FULL OUTER JOIN (
    SELECT 
        TABFU.KOFU AS CODIGO_VENDEDOR,
        TABFU.NOKOFU AS NOMBRE_VENDEDOR,
        COUNT(*) AS TOTAL_FACTURAS_PENDIENTES,
        SUM(CASE 
            WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
            ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
        END) AS SALDO_FACTURAS_PENDIENTE
    FROM dbo.TABFU 
    RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
    RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
    WHERE (dbo.MAEEDO.EMPRESA = '01') 
        AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
        AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
        AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
        AND TABFU.KOFU IS NOT NULL
    GROUP BY TABFU.KOFU, TABFU.NOKOFU
) f ON n.CODIGO_VENDEDOR = f.CODIGO_VENDEDOR
ORDER BY TOTAL_DOCUMENTOS DESC, VALOR_TOTAL_PENDIENTE DESC;

-- Query 5: Verificar si existe el vendedor GOP (que aparecía en los datos de ejemplo)
SELECT 
    TABFU.KOFU AS CODIGO_VENDEDOR,
    TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    COUNT(DISTINCT MAEDDO.IDMAEDDO) AS TOTAL_NVV_PENDIENTES,
    COUNT(DISTINCT MAEEDO.IDMAEDO) AS TOTAL_FACTURAS_PENDIENTES
FROM dbo.TABFU 
LEFT JOIN dbo.MAEDDO ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
    AND (dbo.MAEDDO.TIDO = 'NVV') 
    AND (dbo.MAEDDO.LILG = 'SI') 
    AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
    AND (dbo.MAEDDO.KOPRCT <> 'D') 
    AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
LEFT JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
LEFT JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
    AND (dbo.MAEEDO.EMPRESA = '01') 
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
WHERE TABFU.KOFU = 'GOP'
GROUP BY TABFU.KOFU, TABFU.NOKOFU;
