-- =============================================
-- Verificar datos de vendedores LCB y GMB
-- GesPro Raviera - Sistema de Ventas
-- =============================================

-- Verificar si existen los vendedores LCB y GMB en TABFU
SELECT 
    KOFU AS CODIGO_VENDEDOR,
    NOKOFU AS NOMBRE_VENDEDOR
FROM dbo.TABFU 
WHERE KOFU IN ('LCB', 'GMB')
ORDER BY KOFU;

-- Verificar NVV pendientes para LCB
SELECT 
    COUNT(*) AS TOTAL_NVV_LCB,
    SUM(MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1) AS UNIDADES_PENDIENTES_LCB,
    SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_PENDIENTE_LCB
FROM dbo.MAEDDO 
INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
WHERE (dbo.MAEDDO.TIDO = 'NVV') 
    AND (dbo.MAEDDO.LILG = 'SI') 
    AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
    AND (dbo.MAEDDO.KOPRCT <> 'D') 
    AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
    AND dbo.TABFU.KOFU = 'LCB';

-- Verificar NVV pendientes para GMB
SELECT 
    COUNT(*) AS TOTAL_NVV_GMB,
    SUM(MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1) AS UNIDADES_PENDIENTES_GMB,
    SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_PENDIENTE_GMB
FROM dbo.MAEDDO 
INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
WHERE (dbo.MAEDDO.TIDO = 'NVV') 
    AND (dbo.MAEDDO.LILG = 'SI') 
    AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
    AND (dbo.MAEDDO.KOPRCT <> 'D') 
    AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
    AND dbo.TABFU.KOFU = 'GMB';

-- Verificar facturas pendientes para LCB
SELECT 
    COUNT(*) AS TOTAL_FACTURAS_LCB,
    SUM(CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
        ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
    END) AS SALDO_TOTAL_PENDIENTE_LCB
FROM dbo.TABFU 
RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
WHERE (dbo.MAEEDO.EMPRESA = '01') 
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
    AND TABFU.KOFU = 'LCB';

-- Verificar facturas pendientes para GMB
SELECT 
    COUNT(*) AS TOTAL_FACTURAS_GMB,
    SUM(CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
        ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
    END) AS SALDO_TOTAL_PENDIENTE_GMB
FROM dbo.TABFU 
RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
WHERE (dbo.MAEEDO.EMPRESA = '01') 
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
    AND TABFU.KOFU = 'GMB';

-- Resumen combinado de ambos vendedores
SELECT 
    TABFU.KOFU AS CODIGO_VENDEDOR,
    TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    ISNULL(nvv.TOTAL_NVV, 0) AS TOTAL_NVV_PENDIENTES,
    ISNULL(nvv.UNIDADES_PENDIENTES, 0) AS UNIDADES_PENDIENTES,
    ISNULL(nvv.VALOR_PENDIENTE, 0) AS VALOR_NVV_PENDIENTE,
    ISNULL(fact.TOTAL_FACTURAS, 0) AS TOTAL_FACTURAS_PENDIENTES,
    ISNULL(fact.SALDO_PENDIENTE, 0) AS SALDO_FACTURAS_PENDIENTE,
    (ISNULL(nvv.TOTAL_NVV, 0) + ISNULL(fact.TOTAL_FACTURAS, 0)) AS TOTAL_DOCUMENTOS,
    (ISNULL(nvv.VALOR_PENDIENTE, 0) + ISNULL(fact.SALDO_PENDIENTE, 0)) AS VALOR_TOTAL_PENDIENTE
FROM dbo.TABFU 
LEFT JOIN (
    SELECT 
        TABFU.KOFU,
        COUNT(*) AS TOTAL_NVV,
        SUM(MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1) AS UNIDADES_PENDIENTES,
        SUM((MAEDDO.VANELI / MAEDDO.CAPRCO1) * (MAEDDO.CAPRCO1 - MAEDDO.CAPRAD1 - MAEDDO.CAPREX1)) AS VALOR_PENDIENTE
    FROM dbo.MAEDDO 
    INNER JOIN dbo.MAEEN ON dbo.MAEDDO.ENDO = dbo.MAEEN.KOEN AND dbo.MAEDDO.SUENDO = dbo.MAEEN.SUEN 
    INNER JOIN dbo.TABFU ON dbo.MAEDDO.KOFULIDO = dbo.TABFU.KOFU 
    WHERE (dbo.MAEDDO.TIDO = 'NVV') 
        AND (dbo.MAEDDO.LILG = 'SI') 
        AND (dbo.MAEDDO.CAPRCO1 - dbo.MAEDDO.CAPRAD1 - dbo.MAEDDO.CAPREX1 <> 0) 
        AND (dbo.MAEDDO.KOPRCT <> 'D') 
        AND (dbo.MAEDDO.KOPRCT <> 'FLETE')
    GROUP BY TABFU.KOFU
) nvv ON TABFU.KOFU = nvv.KOFU
LEFT JOIN (
    SELECT 
        TABFU.KOFU,
        COUNT(*) AS TOTAL_FACTURAS,
        SUM(CASE 
            WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
            ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
        END) AS SALDO_PENDIENTE
    FROM dbo.TABFU 
    RIGHT OUTER JOIN dbo.MAEEN ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN 
    RIGHT OUTER JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO 
    WHERE (dbo.MAEEDO.EMPRESA = '01') 
        AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV') 
        AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2000-01-01 00:00:00', 102)) 
        AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO)
        AND TABFU.KOFU IS NOT NULL
    GROUP BY TABFU.KOFU
) fact ON TABFU.KOFU = fact.KOFU
WHERE TABFU.KOFU IN ('LCB', 'GMB')
ORDER BY TABFU.KOFU;
