-- Vista para cobranza por vendedor
-- Esta vista incluye toda la lógica de negocio para calcular estados, saldos, etc.

CREATE VIEW vw_cobranza_por_vendedor AS
SELECT 
    dbo.MAEEDO.TIDO AS TIPO_DOCTO,
    dbo.MAEEDO.NUDO AS NRO_DOCTO,
    dbo.MAEEDO.ENDO AS CODIGO_CLIENTE,
    dbo.MAEEN.NOKOEN AS NOMBRE_CLIENTE,
    dbo.MAEEDO.SUDO AS SUCURSAL,
    dbo.MAEEDO.FEEMDO AS FECHA_EMISION,
    dbo.MAEEDO.FE01VEDO AS PRIMER_VENCIMIENTO,
    dbo.MAEEDO.FEULVEDO AS ULTIMO_VENCIMIENTO,
    CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) AS DIAS_VENCIDO,
    dbo.MAEEN.FOEN AS TELEFONO,
    dbo.MAEEN.DIEN AS DIRECCION,
    dbo.TABCI.NOKOCI AS REGION,
    dbo.TABCM.NOKOCM AS COMUNA,
    dbo.TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    dbo.TABFU.KOFU AS CODIGO_VENDEDOR,
    
    -- Cálculo de valores
    CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN dbo.MAEEDO.VABRDO * -1 
        ELSE dbo.MAEEDO.VABRDO 
    END AS VALOR_DOCUMENTO,
    
    CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN dbo.MAEEDO.VAABDO * -1 
        ELSE dbo.MAEEDO.VAABDO 
    END AS ABONOS,
    
    -- Cálculo de saldo
    CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
        ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
    END AS SALDO,
    
    -- Estado del documento
    CASE 
        WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) < -8 THEN 'VIGENTE'
        WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN -7 AND -1 THEN 'POR VENCER'
        WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN 0 AND 7 THEN 'VENCIDO'
        WHEN CAST(GETDATE() - dbo.MAEEDO.FEULVEDO AS INT) BETWEEN 8 AND 30 THEN 'MOROSO'
        ELSE 'BLOQUEAR'
    END AS ESTADO_DOCUMENTO,
    
    dbo.MAEEDO.EMPRESA

FROM dbo.MAEEDO 
INNER JOIN dbo.MAEEN ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO
INNER JOIN dbo.TABFU ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN
LEFT JOIN dbo.TABCI ON dbo.MAEEN.CIEN = dbo.TABCI.KOCI
LEFT JOIN dbo.TABCM ON dbo.MAEEN.CIEN = dbo.TABCM.KOCI AND dbo.MAEEN.CMEN = dbo.TABCM.KOCM

WHERE (dbo.MAEEDO.EMPRESA = '01' OR dbo.MAEEDO.EMPRESA = '02')
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV')
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2017-12-31 00:00:00', 102))
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO); 