-- Vista para resumen de clientes por vendedor
CREATE VIEW vw_clientes_por_vendedor AS
SELECT 
    dbo.MAEEN.KOEN AS CODIGO_CLIENTE,
    dbo.MAEEN.NOKOEN AS NOMBRE_CLIENTE,
    dbo.MAEEN.FOEN AS TELEFONO,
    dbo.MAEEN.DIEN AS DIRECCION,
    dbo.TABCI.NOKOCI AS REGION,
    dbo.TABCM.NOKOCM AS COMUNA,
    dbo.TABFU.KOFU AS CODIGO_VENDEDOR,
    dbo.TABFU.NOKOFU AS NOMBRE_VENDEDOR,
    COUNT(dbo.MAEEDO.NUDO) AS CANTIDAD_FACTURAS,
    SUM(CASE 
        WHEN dbo.MAEEDO.TIDO = 'NCV' THEN (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) * -1 
        ELSE (dbo.MAEEDO.VABRDO - dbo.MAEEDO.VAABDO) 
    END) AS SALDO_TOTAL

FROM dbo.MAEEN
LEFT JOIN dbo.TABCI ON dbo.MAEEN.CIEN = dbo.TABCI.KOCI
LEFT JOIN dbo.TABCM ON dbo.MAEEN.CIEN = dbo.TABCM.KOCI AND dbo.MAEEN.CMEN = dbo.TABCM.KOCM
LEFT JOIN dbo.MAEEDO ON dbo.MAEEN.KOEN = dbo.MAEEDO.ENDO AND dbo.MAEEN.SUEN = dbo.MAEEDO.SUENDO
INNER JOIN dbo.TABFU ON dbo.TABFU.KOFU = dbo.MAEEN.KOFUEN

WHERE (dbo.MAEEDO.EMPRESA = '01' OR dbo.MAEEDO.EMPRESA = '02' OR dbo.MAEEDO.EMPRESA IS NULL)
    AND (dbo.MAEEDO.TIDO = 'NCV' OR dbo.MAEEDO.TIDO = 'FCV' OR dbo.MAEEDO.TIDO = 'FDV' OR dbo.MAEEDO.TIDO IS NULL)
    AND (dbo.MAEEDO.FEEMDO > CONVERT(DATETIME, '2017-12-31 00:00:00', 102) OR dbo.MAEEDO.FEEMDO IS NULL)
    AND (dbo.MAEEDO.VABRDO > dbo.MAEEDO.VAABDO OR dbo.MAEEDO.VABRDO IS NULL)

GROUP BY 
    dbo.MAEEN.KOEN, 
    dbo.MAEEN.NOKOEN, 
    dbo.MAEEN.FOEN, 
    dbo.MAEEN.DIEN, 
    dbo.TABCI.NOKOCI, 
    dbo.TABCM.NOKOCM,
    dbo.TABFU.KOFU,
    dbo.TABFU.NOKOFU; 